# Reconstruct a tomogram from one MissAlignment iteration snapshot.
# Arguments: PROJECT_DIRECTORY ITERATION ANGPIX

universe = vanilla
executable = run_warp_reconstruction.sh
arguments = /staging/hzhan3/warp-miss-alignment-test/2810_g1/output_TS_2_run001 8 12

log = logs/warp_reconstruction_$(Cluster)_$(Process).log
error = logs/warp_reconstruction_$(Cluster)_$(Process).err
output = logs/warp_reconstruction_$(Cluster)_$(Process).out

container_image = osdf:///chtc/staging/hzhan3/warp-miss-alignment.sif
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

requirements = (HasCHTCStaging == true)
+WantGPULab = true
+GPUJobLength = "medium"

request_gpus = 1
gpus_minimum_memory = 10000M
request_cpus = 4
request_memory = 32GB
request_disk = 40GB

queue 1
